DROP TABLE IF EXISTS TBL_CUSTOMER;
  
CREATE TABLE TBL_CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  phone_no VARCHAR(12) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_DRIVER;
  
CREATE TABLE TBL_DRIVER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  phone_no VARCHAR(12) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_CUSTOMER_DRIVER;
  
CREATE TABLE TBL_CUSTOMER_DRIVER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  driver_name VARCHAR(250) NOT NULL, 
  customer_name VARCHAR(250) DEFAULT NULL,
  status VARCHAR(250) NOT NULL,
);

